bazinga_geocoder:
    providers:
        google_maps:
            factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
#            cache: 'app.bazinga.geocoder_cache'
#            cache_lifetime: 5356800 # 3 months
#            cache_precision: ~
            options:
                api_key: "%env(GMAPS_API_KEY)%"
