monolog:
    handlers:
        main:
            type:                   fingers_crossed
            action_level:           error
            activation_strategy:    app.logging.activation_strategy
            handler:                sentry
            stop_buffering:         false
        sentry:
            type:                   service
            id:                     app.logging.sentry_handler
        console:
            type:                   console
